### PR TITLE
rebase of rails3 upgrades onto annotation-interface

### PR DESCRIPTION
**Pull request by jywarren**
This code has been merged and discussion is now happening at https://github.com/jywarren/mapknitter/pull/181

<strike>This is not ready for adoption yet but is a place to track progress; but it is getting closer to working code. The rebase was pretty easy; some additional work will be needed to get things running, then we need to decide on a course of action for merging this code into master -- mostly a checklist for preserving data and ensuring feature continuity for existing users.

<strike>So, my understanding is that [the annotation-interface pull request](https://github.com/publiclab/mapknitter/pull/22) is not ready for production, but my hope is that we can reintegrate that branch into ongoing development work either:

<strike>a) by separating it into its own "beta" interface while continuing to provide fully functional tools to existing users. It looks like to some degree that has been tackled by @manleyjster, as I see "betawarper" and other beta-notated code
<strike>b) testing the new version on a copy of the entire system (maybe on a smaller VM to save $) and getting OKs from users before attempting a migration -- but basically just getting everything done fast (not ideal, obviously, but potentially cleaner) and ensuring complete feature parity before doing an all-at-once migration

<strike>Some necessary considerations before this code can be accepted:

<strike>1. [ ] there has always been a very strong community-driven priority on keeping the ability to create maps without a login, for anonymity reasons: there have been in-depth discussions on the Public Lab organizers list, but some comments here as well: https://github.com/publiclab/mapknitter/issues/9#issuecomment-53583611
<strike>    \* [ ] the new code seems to eliminate that function; we'll likely need to reinstate it unless community discussion backs a change
<strike>2. [x] preservation of existing annotations in annotation_controller -- what happens to old annotations? If they're viewable in a legacy mode, this could be moved to the below list
<strike>3. [x] map URLs are numeric id-based in this branch, which breaks previous map URLs. I propose preserving the legacy route with a HTTP redirect (so that search engines etc eventually update) and using a new route such as "/map/#" instead of "/maps/#" for the new convention. 
<strike>4. [ ] ensure correct ordering of db migrations; this may require some renaming to get the timestamps in an order so that the production server doesn't choke when we migrate. 

<strike>And considerations which we could take more time to address if we move the new pure-Leaflet interface to be a parallel "beta" without yet eliminating the legacy interface:

<strike>1. [ ] plan for consolidating similarly-named controllers; does new tag infrastructure (controller, etc) preserve old tags? (just checking)
<strike>    \* [ ] similar code in uploads, warper, betawarper and warpables_controllers
<strike>2. [ ] Reviewing the distinction between what were formerly called the 'view' page and the 'show' (edit) page. [Justin's discussion and UI work](http://publiclab.org/notes/justinmanley/08-06-2014/mapknitter-annotations-interface-refactoring) proposing to cut the view (he calls it overview) page in favor of what we used to do -- let users immediately see the full screen map -- can work if the map is read-only, esp. with the nice new sidebar Justin created. So we'd need a really clear indicator/switch for going into edit mode. This also jives nicely with a completely Leaflet interface, now that we're finally getting ready to ditch the OpenLayers/Cartagen frankenstein code. 
<strike>    \* [x] We will have to redirect /map/view/foo to /map/#, and it seems reasonable to always default to read-only until you click Edit or **Edit mode**. 
<strike>3. [ ] merging the `app/views/map/leaflet.html.erb` code (pretty simple) into the new `app/views/maps/show.html.erb` page
<strike>    \* [ ] finishing the new Leaflet.DistortableImage UI work and ensuring feature parity

<strike>I'm still in the midst of this integration work, but just wanted to put this all on the record and solicit input from Justin and others. I'm sure I've forgotten things here, but it's a start. Also, if it's easier to structure this PR differently and actually do it vs. publiclab master, please suggest any more efficient plan here. Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
fixed openid issues; was a restful routing oddity; form template code in `app/views/layouts/_header.html.erb` wasn't hitting the right route/params for the open_id_authentication gem. Hand-coded the form tag, now it works.

**Comment by jywarren** [comment]
Preserving legacy routes at `/maps/foo` by substituting `/map/#` breaks the automated resourceful-based link_to generator; we could probably override, but raw HTML is reasonable for now.

**Comment by jywarren** [comment]
Hmm, resourceful map generation on maps/create is generating a weird route:

`No route matches {:controller=>"warpables", :format=>nil, :map_id=>#<Map id: nil, name: "", lat: #<BigDecimal:b4a16bc0,'0.0',9(27)>, lon: #<BigDecimal:b4a16b84,'0.0',9(27)>, version: 1, password: "", styles: nil, created_at: nil, updated_at: nil, description: nil, author: "warren", zoom: #<BigDecimal:b4a16a08,'0.2E1',9(27)>, location: "", static_data: "", vectors: false, tiles: "google", email: "", archived: false, tile_url: "", tile_layer: "", license: "copyright", user_id: 1, anon_annotatable: false>}`

Going to put this aside for the night, but stuff is getting closer. The upload interface seems not to be loading in its modal, will look at that too. (update: fixed that too; form_for now requires `<%=` to display)

**Comment by justinmanley** [comment]
I did neglect the anonymous login functionality - but I wasn't making a reasoned choice to delete that functionality. I believe that I left an option for anonymous login when I redesigned the interface, but I didn't change the controller, so that functionality should still be there under the hood - we just need to add it back in to the interface.

I moved from string-based to numeric map urls (i.e. the `/maps/id#` urls) because that aligns very neatly with Rails' resourceful routing. I wanted to use [`friendly_id`](https://github.com/norman/friendly_id) to generate urls based on the names of the maps, rather than their numeric ids. That wasn't possible with Rails 2 (or 1, or whatever we were using before) b/c friendly_id wasn't compatible, but with the upgrade to Rails 3, we should be able to use friendly_id!  So that solves that problem!

**Comment by jywarren** [comment]
OK -- I made the routes:

```
get 'maps/:id' => 'maps#show', defaults: { legacy: true } # legacy
get 'map/:id' => 'maps#show', :as => 'map'
```

So all the route helpers and behaviors work with the numeric version for now, but before we deploy we should integrate friendly_id. I'll add that to the checklist. For reference, I'm assuming we can backport slugs of old maps into friendly_id or otherwise accommodate existing maps/foo style legacy map permalinks?

As soon as we resolve this, let's move discussion over to https://github.com/jywarren/mapknitter/pull/181, or to its own issue, sound all right?

**Pull request merged**
